export const solicitorDirectory = [
  {
    id: "elaine-foster",
    name: "Elaine Foster",
    specialty: "Family Law",
    rating: 4.9,
    location: "London",
    experience: 12,
    hourlyRate: 240,
    consultationFee: 80,
    verified: true,
    availability: true,
    firmName: "Foster Legal Chambers",
    serviceModes: ["Virtual", "In Person"],
    languages: ["English", "French"],
    responseTime: "Responds within 4 hours",
    bio: "Elaine advises clients on divorce, child arrangements, and mediation strategy with a calm, pragmatic approach.",
  },
  {
    id: "daniel-webb",
    name: "Daniel Webb",
    specialty: "Corporate Law",
    rating: 4.8,
    location: "Manchester",
    experience: 10,
    hourlyRate: 275,
    consultationFee: 95,
    verified: true,
    availability: true,
    firmName: "Webb Business Counsel",
    serviceModes: ["Virtual"],
    languages: ["English"],
    responseTime: "Responds within 8 hours",
    bio: "Daniel supports founders and SMEs on contracts, shareholder matters, and commercial risk reduction.",
  },
  {
    id: "sophie-carter",
    name: "Sophie Carter",
    specialty: "Immigration",
    rating: 4.7,
    location: "Birmingham",
    experience: 9,
    hourlyRate: 210,
    consultationFee: 70,
    verified: true,
    availability: false,
    firmName: "Carter Migration Partners",
    serviceModes: ["Virtual", "In Person"],
    languages: ["English", "Arabic"],
    responseTime: "Responds within 12 hours",
    bio: "Sophie handles visa appeals, sponsorship issues, and complex residency pathways for individuals and families.",
  },
  {
    id: "mark-bennett",
    name: "Mark Bennett",
    specialty: "Property Law",
    rating: 4.6,
    location: "Leeds",
    experience: 14,
    hourlyRate: 230,
    consultationFee: 85,
    verified: false,
    availability: true,
    firmName: "Bennett Property Advisory",
    serviceModes: ["In Person"],
    languages: ["English"],
    responseTime: "Responds within 24 hours",
    bio: "Mark focuses on residential transactions, landlord disputes, and due diligence for property buyers.",
  },
];

export const searchFilters = {
  specialties: ["Family Law", "Corporate Law", "Immigration", "Property Law"],
  locations: ["London", "Manchester", "Birmingham", "Leeds"],
  serviceModes: ["Virtual", "In Person"],
  sortOptions: [
    { value: "rating", label: "Top rated" },
    { value: "experience", label: "Most experienced" },
    { value: "price_low", label: "Price: low to high" },
    { value: "price_high", label: "Price: high to low" },
  ],
};

