# Generated by Django 5.2.12 on 2026-03-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_issue', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('urgency', models.CharField(max_length=50)),
                ('budget_band', models.CharField(blank=True, max_length=50)),
                ('service_mode', models.CharField(blank=True, max_length=50)),
                ('language_preference', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=50)),
                ('needs_verified_solicitor', models.BooleanField(default=True)),
                ('needs_immediate_availability', models.BooleanField(default=False)),
                ('case_summary', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
