# Generated by Django 5.2.12 on 2026-03-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('solicitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsolicitor',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_customers', to='solicitors.solicitorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsolicitor',
            unique_together={('customer', 'solicitor')},
        ),
    ]
